name: CI/CD - API (Azure Functions Python)

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      # 1. Récupération du code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. (Optionnel) Lancer les tests unitaires
      - name: Run unit tests
        run: pytest || echo "No tests found, skipping"

      # 5. Authentification Azure avec Service Principal
      - name: Azure Login (RBAC)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 6. Déploiement sur Azure Functions
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.FUNCTIONAPP_NAME }}
          package: ${{ github.workspace }}/backend
          respect-funcignore: true
