name: Deploy Backend (Azure Functions Python)

on:
  push:
    branches:
      - main   # déploiement à chaque push sur main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend   # toutes les commandes se lancent dans backend/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"   # ajuste à ta version locale

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: func-azmeter-api   # ⚡ le nom exact de ton Function App
          package: ./backend           # 👉 important, déploie uniquement ton backend
