name: CI/CD - Azure Functions Python

on:
  push:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Installer dépendances
      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Lancer les tests (optionnel si tu as pytest)
      - name: Run tests
        run: |
          cd backend
          pytest || echo "No tests"

      # 5. Login Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 6. Installer Azure Functions Core Tools
      - name: Install Azure Functions Core Tools
        run: |
          sudo npm install -g azure-functions-core-tools@4 --unsafe-perm true

      # 7. Déploiement avec func CLI
      - name: Deploy with Azure Functions Core Tools
        run: |
          cd backend
          func azure functionapp publish func-azmeter-api
